begin;
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (3, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (4, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (5, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (6, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (7, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (8, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (9, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (10, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (11, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (12, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (13, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (14, 1);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (15, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (16, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (17, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (18, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (19, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (20, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (21, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (22, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (23, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (24, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (25, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (26, 2);
INSERT INTO "master_product_option" ("product_id", "option_id") VALUES (104, 3);
commit;